apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-postgres-configmap
data:
  POSTGRES_USER: {{ .Values.credentials.userName }}
  POSTGRES_PASSWORD: {{ .Values.credentials.usePwd }}
  POSTGRES_DB: {{ .Values.credentials.dbName }}
  MIN_REPLICAS: {{ .Values.replicas.min }}
  MAX_REPLICAS: {{ .Values.replicas.max }}
  REQUEST_CPU: {{ .Values.resources.request.cpu }}
  REQUEST_MEMORY: {{ .Values.resources.request.memory }}
  LIMIT_CPU: {{ .Values.resources.limit.cpu }}
  LIMIT_MEMORY: {{ .Values.resources.limit.memory }}
env:
  GOOGLE_RECAPTCHA_URL: {{ .Values.env.GOOGLE_RECAPTCHA_URL | quote }}
  ENABLE_RECAPTCHA: {{ .Values.env.ENABLE_RECAPTCHA }}
  BUCKET_NFE: {{ .Values.env.BUCKET_NFE | quote }}