apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-postgres-configmap
data:
  POSTGRES_DB: {{ .Values.postgre.credentials.dbName | quote }}
  POSTGRES_USER: {{ .Values.postgre.credentials.userName | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgre.credentials.usePwd | quote }}
