apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-secrets
type: Opaque
data:
  POSTGRES_DB: {{ .Values.postgre.credentials.dbName | b64enc | quote }}
  POSTGRES_USER: {{ .Values.postgre.credentials.userName | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgre.credentials.usePwd | b64enc | quote }}