postgre:
  tag: "16.1"
  credentials:
    usePwd: "tonystark@123"
    userName: "descoshop"
    dbName: "descoshop-prod"
  service:
    type: LoadBalancer
    port: 5432
    targetPort: 5432
    selector: 
      app: descoshop-prod-rds
  replicas:
    min: 4
    max: 10
  resources:
    request:
      cpu: "200m"
      memory: "192Mi"
    limit:
      cpu: "400m"
      memory: "512Mi"
  env:
    GOOGLE_RECAPTCHA_URL: "https://google.com/recaptcha/api"
    ENABLE_RECAPTCHA: true
    BUCKET_NFE: "https://s3.console.aws.amazon.com/s3/home?region=us-east-1#"

ingress:
  enabled: true
  name: descoshop-prod-rds
  spec:
    ingressClassName: ""
    annotations:
      nginx.ingress.kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: "letsencrypt"
    tls:
      - hosts:
          - descoshop-prod.rds.aws.amazon.com
        secretName: descoshop-rds-tls
    rules:
      - http:
          paths:
            - path: /descoshop-prod-rds
              pathType: Prefix
              backend:
                service:
                  name: descoshop-prod-rds
                  port:
                    number: 80