apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgres-deploy
spec:
  replicas: {{ .Values.replicas.min }}
  selector:
    matchLabels:
      app: postgres-deploy
  tamplate:
    metadata:
      labels:
        app: postgres-deploy
    spec:
      containers:
      - name: postgres
        image: {{ .Values.container.image }}
        ports:
        - containerPort: 5432
        env:
          - name: POST_USER
            value: {{ .Values.database.user }}
          - name: POSTGGRES_PASSWORD
            value: {{ .Values.database.password }}
          - name: POSTGRES_URL
            value: {{ .Values.database.name }}
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
        limits:
          cpu: {{ .Values.resources.limits.cpu }}
          memory: {{ .Values.resources.limits.memory }}
          