postgre:
  tag: "16.1"
  credentials:
    usePwd: "tonystark@123"
    userName: "descoshop"
    dbName: "descoshop-stg"
  service:
    type: ClusterIP
    port: 5432
    targetPort: 5432
  replicas:
    min: 1
    max: 4
  resources:
    request:
      cpu: "200m"
      memory: "192Mi"
    limit:
      cpu: "400m"
      memory: "512Mi"
  env:
    GOOGLE_RECAPTCHA_URL: "https://google.com/recaptcha/api"
    ENABLE_RECAPTCHA: true
    BUCKET_NFE: "URL do S3 criado na próxima etapa"
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt"
