postgre:
  tag: "16.1"
  credentials:
    usePwd: "tonystark@123"
    userName: "descoshop"
    dbName: "descoshop-stg"
  service:
    type: LoadBalancer
    port: 5432
    targetPort: 5432
  replicas:
    min: 1
    max: 4
  resources:
    request:
      cpu: "200m"
      memory: "192Mi"
    limit:
      cpu: "400m"
      memory: "512Mi"
  env:
    GOOGLE_RECAPTCHA_URL: "https://google.com/recaptcha/api"
    ENABLE_RECAPTCHA: true
    BUCKET_NFE: "https://s3.console.aws.amazon.com/s3/home?region=us-east-1#"
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt"