postgre:
  tag: "16.1"
  credentials:
    usePwd: "tonystark@123"
    userName: "descoshop"
    dbName: "descoshop-stg"
  replicas:
    min: 1
    max: 4
  resources:
    request:
      cpu: "200m"
      memory: "192Mi"
    limit:
      cpu: "400m"
      memory: "512Mi"
env:    
  GOOGLE_RECAPTCHA_URL: "https://google.com/recaptcha/api"
  ENABLE_RECAPTCHA: true
  BUCKET_NFE: ""