apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-postgre-configmap
data:
  POSTGRES_DB: {{ .Values.postgre.credentials.dbName | quote }}
  POSTGRES_USER: {{ .Values.postgre.credentials.userName | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgre.credentials.usePwd | quote }}
  GOOGLE_RECAPTCHA_URL: {{ .Values.postgre.env }}
  ENABLE_RECAPTCHA: {{ .Values.postgre.env }}
  BUCKET_NFE: {{ .Values.postgre.env }}