apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgre-secrets
type: Opaque
data:
  POSTGRES_DB: {{ .Values.postgre.credentials.dbName | b64enc | quote }}
  POSTGRES_USER: {{ .Values.postgre.credentials.userName | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgre.credentials.usePwd | b64enc | quote }}
  GOOGLE_RECAPTCHA_URL: {{ .Values.postgre.env.GOOGLE_RECAPTCHA_URL | default "" | toString | b64enc | quote }}
  ENABLE_RECAPTCHA: {{ .Values.postgre.env.ENABLE_RECAPTCHA | default "false" | toString | b64enc | quote }}
  BUCKET_NFE: {{ .Values.postgre.env.BUCKET_NFE | default "" | toString | b64enc | quote }}
