# descoshop-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-descoshop
spec:
  replicas: {{ .Values.replicas.min }}
  selector:
    matchLabels:
      app: descoshop
  template:
    metadata:
      labels:
        app: descoshop
    spec:
      containers:
      - name: descoshop
        image: thser/descoshop:latest
        resources:
          requests:
            memory: {{ .Values.resources.request.memory }}
            cpu: {{ .Values.resources.request.cpu }}
          limits:
            memory: {{ .Values.resources.limit.memory }}
            cpu: {{ .Values.resources.limit.cpu }}
        env:
        - name: GOOGLE_RECAPTCHA_URL
          value: {{ .Values.recaptcha_url }}
        - name: ENABLE_RECAPTCHA
          value: {{ .Values.enable_recaptcha }}
        - name: BUCKET_NFE
          value: {{ .Values.bucket_nfe }}
