apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nodeapp
spec:
  replicas: {{ .Values.nodeapp.replicas.min }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-nodeapp
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-nodeapp
    spec:
      containers:
      - name: nodeapp
        image: node:{{ .Values.nodeapp.tag }}
        ports:
        - containerPort: {{ .Values.nodeapp.service.port }}
        resources:
          requests:
            memory: {{ .Values.nodeapp.resources.request.memory }}
            cpu: {{ .Values.nodeapp.resources.request.cpu }}
          limits:
            memory: {{ .Values.nodeapp.resources.limit.memory }}
            cpu: {{ .Values.nodeapp.resources.limit.cpu }}