{{ if .Values.nodeapp.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: {{ .Values.ingress.annotations.certManagerClusterIssuer }}
spec:
  ingressClassName: {{ .Values.nodeapp.ingress.className }}
  rules:
  {{- range.Values.nodeapp.ingress.hosts }}
  tls:
  - hosts:
    - {{ . }}
    secretName: {{ . }}nodeapp-tls
  - host: {{ . }}
    http:
      paths:
      - path: /nodeapp
        pathType: Prefix
        backend:
          service:
            name: {{ $.Release.Name }}-nodeapp
            port:
              number: {{ .Values.nodeapp.service.port }}
  {{- end }}
{{ end }}
