nodeapp:
  tag: "18"
  service:
    type: LoadBalancer
    port: 80
    targetPort: 80
    selector:
      app: nodeapp
  replicas:
    min: 1
    max: 4
  resources:
    request:
      cpu: "200m"
      memory: "192Mi"
    limit:
      cpu: "400m"
      memory: "512Mi"

ingress:
  enabled: true
  name: nodeapp
  spec:
    ingressClassName: ""
    annotations:
      nginx.ingress.kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: "letsencrypt"
    tls:
      - hosts:
          - descoshop-stg.rds.aws.amazon.com 
        secretName: nodeapp-tls
    rules:
      - http:
          paths:
            - path: /nodeapp
              pathType: Prefix
              backend:
                service:
                  name: nodeapp
                  port:
                    number: 80
