apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "go.fullname" . }}-go
  labels:
    {{- include "go.labels" . | nindent 4 }}-go
spec:
  replicas: {{ .Values.replicas.min }}
  selector:
    matchLabels:
      app: {{ include "go.fullname" . }}-go
  template:
    metadata:
      labels:
        app: {{ include "go.fullname" . }}-go
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
              name: descoshop
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
