
{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "go.fullname" . }}
  labels:
    {{- include "go.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  ingressClassName:
  rules:
  tls:
    - hosts:
        - {{ . }}
      secretName: {{ include "go.fullname" . }}-go-tls
    - host: {{ . }}
      http:
        paths:
          - path: /descoshop
            pathType: Prefix
            backend:
              service:
                name: {{ include "go.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{ end }}