
{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.name }}
  annotations:
    nginx.ingress.kubernetes.io/ingress.class: {{ .Values.ingress.annotations }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.annotations.certManagerClusterIssuer }}
spec:
  ingressClassName: {{ .Values.go.ingress.className }}
  rules:
  {{- range.Values.go.ingress.hosts }}
  tls:
    - hosts:
      - {{ . }}
      secretName: {{ . }}-go-tls
    - host: {{ . }}
      http:
        paths:
          - path: /descoshop
            pathType: Prefix
            backend:
              service:
                name: {{ $.Release.Name }}-go
                port:
                  number: {{ .Values.service.port }}
  {{- end }}
{{ end }}