name: Build and push Docker image to Docker registry

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install kubectl
        uses: azure/setup-kubectl@v2.0
        with:
          version: 'v1.29.0'
        id: install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Docker build and push
        run: |
          docker build -t node-app .
          docker tag node-app thsre/node-app:latest
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push thsre/node-app:latest
        env:
          DOCKER_CLI_ACI: 1
          
      - name: Trivy image scan
        run: trivy image thsre/node-app:latest

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name matrix-prod --region us-east-1

      - name: Deploy nodejs Helm chart to EKS
        run: |
          helm install postgres ./descoshop
          helm install node ./nodeapp 