name: Build and push Docker image to Docker registry

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install kubectl
        uses: azure/setup-kubectl@v2.0
        with:
          version: 'v1.29.0'
        id: install

      - name: Docker build and push
        run: |
          docker build -t node-app .
          docker tag node-app thsre/node-app:latest
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push thsre/node-app:latest
        env:
          DOCKER_CLI_ACI: 1

      - name: Deploy nodejs Helm chart to k8s
        run: |
          helm install postgres ./descoshop
          helm install node ./nodeapp 
